services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: quizbot
    ports:
      - "3306:3306"
  quizbot:
    build: .
    network_mode: "host"
    volumes:
      - "./src/main/resources/config.properties:/app/target/classes/config.properties"
    depends_on:
      - mysql